Repository British-Oceanographic-Data-Centre/COAsT, pull requests merged in 2020-10, with the labels that each got.

#195 Fixes to work with TRANSECT class
  coast/INTERNALTIDE.py
  example_scripts/internal_tide_pycnocline_diagnostics.py
Labels: Internaltide, Transports

#188 0161/transect restructure
  coast/INTERNALTIDE.py
  coast/TRANSECT.py
  coast/__init__.py
  example_scripts/internal_tide_pycnocline_diagnostics.py
  unit_testing/unit_test.py
Labels: Transports

#204 Landmasking added for obs_operator
  coast/ALTIMETRY.py
  coast/NEMO.py
  coast/TIDEGAUGE.py
  coast/general_utils.py
  unit_testing/unit_test.py
Labels: enhancement

#225 0026/eof
  coast/__init__.py
  coast/eof.py
  unit_testing/unit_test.py
  unit_testing/unit_test_contents.txt
Labels: CEOF
