Repository British-Oceanographic-Data-Centre/COAsT, pull requests merged in 2020-09, with the labels that each got.

#140 Compute pycnocline depth and thickness
  coast/DIAGNOSTICS.py
  coast/INTERNALTIDE.py
  coast/NEMO.py
  coast/__init__.py
  example_scripts/internal_tide_pycnocline_diagnostics.py
  unit_testing/unit_test.py
  unit_testing/unit_test_contents.txt
Labels: Internaltide, MODEL

#148 Remove references/aliases from metadata YAML output
  metadata.py
Labels: bug

#164 Example plot scripts for new configs + transect/plot_map()
  coast/TRANSECT.py
  example_scripts/AMM15_example_plot.py
  example_scripts/BLZ_example_plot.py
  example_scripts/SEAsia_R12_example_plot.py
  example_scripts/WCSSP_India_example_plot.py
  unit_testing/unit_test.py
Labels: Plotting

#177 Add logging to file to unit testing
  .gitignore
  unit_testing/unit_test.py
Labels: enhancement

#173 Withdraw support for Python 3.6
  conda/conda_build_config.yaml
  setup.py
Labels: good first issue

#184 0070/isobath contour
  coast/CONTOUR.py
  coast/NEMO.py
  coast/TRANSECT.py
  coast/__init__.py
  requirements.txt
  setup.py
  unit_testing/unit_test.py
  unit_testing/unit_test_contents.txt
Labels: Transports
